### ISSUE TITLE
Peer Review Audit Actions Points

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/core-mx-life-bonding-sc#10]
Got the SC Peer Reviewed and the following Feedback was sent.

```
I had a brief look to better understand the bonding myself and overall looks pretty solid

One thing I am wondering is what stops from someone using the 'withdraw' function for a token<>nonce combination not associated with them – did not see any caller or accepted_addresses checks there

In some places (like 'sanction' endpoint) I saw subtractions with a penalty_amount where the penalty might be higher than 'minued' amount, potentially resulting in underflow, but i think the VM handles it safely by throwing an error. may be better to do checks before

Other than that I did not see anything severe, but of course pls don't take this as a complete review
```

Action Points:
- [x] One thing I am wondering is what stops from someone using the 'withdraw' function for a token<>nonce combination not associated with them – did not see any caller or accepted_addresses checks there
- [x]  In some places (like 'sanction' endpoint) I saw subtractions with a penalty_amount where the penalty might be higher than 'minued' amount, potentially resulting in underflow, but i think the VM handles it safely by throwing an error. may be better to do checks before

**Comment by bucurdavid** [comment]
Action points:
1.  Yes you are right, it should have the check that caller is the bond owner
2. There is a require that checks that the remaining_amount is >= penalty_amount
<img width="543" alt="image" src="https://github.com/Itheum/core-mx-life-bonding-sc/assets/46384319/ebca54e6-6441-41d9-97e0-77c08e9bfff0">

**Comment by damienen** [comment]
Done. Closing.
